header:
  version: 8

local_conf_header:
  wifi: |
    DISTRO_FEATURES_append = " wifi"
  nxp-specific: |
    ACCEPT_FSL_EULA = "1"
    UBOOT_ENTRYPOINT_imx = "0x80008000"
    FIT_ADDR_imx = "0x86000000"
    DEFAULTTUNE_imx = "cortexa7thf-neon"
    KERNEL_MODULE_AUTOLOAD_imx += " brcmfmac g_ether"
    WKS_FILES_imx = "swu-imx.wks"
    EXTRA_IMAGEDEPENDS += "imx-usb-loader-native"
