header:
  version: 8

local_conf_header:
  wifi: |
    DISTRO_FEATURES_append = " wifi"
  nxp-specific: |
    ACCEPT_FSL_EULA = "1"
    UBOOT_ENTRYPOINT = "0x80008000"
    FIT_ADDR = "0x86000000"
    DEFAULTTUNE = "cortexa7thf-neon"
    KERNEL_MODULE_AUTOLOAD_append = " brcmfmac g_ether"
    WKS_FILES = "swu-imx.wks"
    EXTRA_IMAGEDEPENDS_append = " imx-usb-loader-native"
