header:
    version: 8
    includes:
        - kas.yml

local_conf_header:
    stm32mp1: |
        FIT_ADDR = "0xc5000000"
        WKS_FILES = "swu-stm32mp1.wks.in"
        BLK_DEVICE = "/dev/mmcblk0"
        UBOOT_STORAGE_DEVICE = ${BLK_DEVICE}
        UBOOT_ENV_ADDR = "0x280000"
        UBOOT_ENV_ADDR_REDUND = "0x300000"
        SWUPDATE_FIRST_ROOTPART = "${BLK_DEVICE}p5"
        SWUPDATE_SECOND_ROOTPART = "${BLK_DEVICE}p6"
        SWUPDATE_DEVICE_HARDWARE_REV = "revC-01"
