header:
    version: 8
    includes:
        - kas.yml

local_conf_header:
    stm32mp1: |
        UBOOT_FITIMAGE_ADDR = "0xc5000000"
        WKS_FILES = "swu-stm32mp1.wks.in"
        BLK_DEVICE = "/dev/mmcblk0"
        UBOOT_STORAGE_DEVICE = "${BLK_DEVICE}"
        UBOOT_ENV_ADDR = "0x280000"
        UBOOT_ENV_ADDR_REDUND = "0x300000"
        SWUPDATE_STORAGE_DEVICE = "${BLK_DEVICE}"
        SWUPDATE_ROOTPART_A = "5"
        SWUPDATE_ROOTPART_B = "6"
        SWUPDATE_ROOTFS_A = "${SWUPDATE_STORAGE_DEVICE}p${SWUPDATE_ROOTPART_A}"
        SWUPDATE_ROOTFS_B = "${SWUPDATE_STORAGE_DEVICE}p${SWUPDATE_ROOTPART_B}"
