#!/bin/sh

_cur_mmcpart=$(fw_printenv rootpart | cut -d "=" -f 2)
if [ "$_cur_mmcpart" -eq 2 ]; then
    _partno=B
else
    _partno=A
fi
echo "SWUPDATE_EXTRA_ARGS=--select=stable,rootfs${_partno} -H warp7:rev0.2 -f /etc/swupdate.cfg" > /tmp/swupdate.env
