#!/bin/sh

_cur_mmcpart=$(fw_printenv rootpart | cut -d "=" -f 2)
if [ "$_cur_mmcpart" -eq 2 ]; then
    _partno=B
else
    _partno=A
fi
SWUPDATE_EXTRA_ARGS="-e stable,rootfs${_partno} -H pico-imx7d:rev1.2 -f /etc/swupdate.cfg"
SWUPDATE_ARGS="-v ${SWUPDATE_EXTRA_ARGS}"

